/* 
 Sketch generated by the Arduino IoT Cloud Thing "Untitled"
 https://create.arduino.cc/cloud/things/5959b807-6d04-4fb2-bbf8-d970cdc25f5d 
 Arduino IoT Cloud Variables description The following variables are automatically generated and updated when changes are made to the Thing
 String message;
 CloudRelativeHumidity humidity;
 CloudTemperature temperature;
 Variables which are marked as READ/WRITE in the Cloud Thing will also have functions which are called when their values are changed from the Dashboard.
 These functions are generated with the Thing and added at the end of this sketch.
*/
#include "thingProperties.h"
#include "DHT.h"
#define DHTpin 2
#define DHTTYPE DHT11
DHT dht(DHTpin,DHTTYPE);
void setup() {
 // Initialize serial and wait for port to open:
 Serial.begin(9600);
 // This delay gives the chance to wait for a Serial Monitor 
without blocking if none is found delay(1500); 
 // Defined in thingProperties.h
 initProperties();
 // Connect to Arduino IoT Cloud
 ArduinoCloud.begin(ArduinoIoTPreferredConnection);
 
 /*
 The following function allows you to obtain more information related to the state of network and IoT Cloud connection and errors the higher number the more granular information you’ll get.
 The default is 0 (only errors).
 Maximum is 4
*/
 setDebugMessageLevel(2);
 ArduinoCloud.printDebugInfo();
}
void loop() {
 ArduinoCloud.update();
 // Your code here 
 float hm = dht.readHumidity();
Serial.print("Humidity");
 Serial.println(hm);
 float temp = dht.readTemperature();
 Serial.print("Temprature");
 Serial.println(temp);
 humidity = hm ; 
 temperature = temp ; 
 message = "Temperature = "+String(temperature)+"Humidity = 
"+String(humidity) ; 
 
 
 
}
/*
 Since Temperature is READ_WRITE variable, onTemperatureChange() is executed every time a new value is received from IoT Cloud.
*/
void onTemperatureChange() {
 // Add your code here to act upon Temperature change
}
/*
 Since Humidity is READ_WRITE variable, onHumidityChange() is executed every time a new value is received from IoT Cloud.
*/
void onHumidityChange() {
 // Add your code here to act upon Humidity change
}
/*
 Since Message is READ_WRITE variable, onMessageChange() is executed every time a new value is received from IoT Cloud.
*/
void onMessageChange() {
 // Add your code here to act upon Message change
}


